on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master


name: Check PR ENV

jobs:
  check:
    name: Check Env
    runs-on:  ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      SUPER_SECRET: ${{ secrets.SLACK_API_TOKEN }}
    steps:
    - shell: bash
      run: |
        echo "$SUPER_SECRET"
